import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RoomProvider } from "@/context/RoomContext";
import { UserProvider } from "@/context/UserContext";
import { ChatProvider } from "@/context/ChatContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RoomProvider>
          <UserProvider>
        <ChatProvider>

          {children}
        </ChatProvider>
          </UserProvider>
          </RoomProvider>
      </body>
    </html>
  );
}
